---
- name: Install Nginx and deploy index.html
  hosts: all
  become: true

  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Copy index.html
      copy:
        src: /path/to/your/repo/index.html
        dest: /var/www/html/index.html
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
