---
- hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Start Nginx container
      docker_container:
        name: my-nginx-container
        image: nginx:latest
        ports:
          - "80:80"
        restart_policy: always
