---
- hosts: localhost
  become: true
  tasks:
    - name: Install python3-pip
      apt:
        name: python3-pip
        update_cache: yes
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Install Docker and tzdata non-interactively
      apt:
        name:
          - docker.io
          - tzdata
        update_cache: yes
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
      vars:
        TZ: "Your/Timezone"  # Set your desired timezone here

    - name: Set timezone non-interactively
      command: echo "{{ TZ }}" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

    - name: Start Nginx container on EC2 instance
      docker_container:
        name: my-nginx-container
        image: nginx:latest
        ports:
          - "80:80"
        restart_policy: always
        api_version: auto
